:scrollbar:
:data-uri:
:toc2:


==  Environment Setup Lab

Assets for this course include a virtual machine preinstalled with the required tools. This VM is provided in VDI format and can be run on your local workstation using VirtualBox. You run the exercises for the labs in this course entirely within the VM.

.Prerequisites
* Installation of the 64-bit VirtualBox application on your local workstation
* A minimum of two 64-bit CPUs and 2 GB RAM dedicated to the VM used in the course

.Lab Assets

There is one lab asset used in this course:

* *bxms-advanced-infrastructure-lab*: A project of resources that are cloned and imported into BPM Central

.VM Components

The `gpte-bxms-advanced-infrastructure-630.vdi` VM image has these characteristics:

* VirtualBox VDI format, built with VirtualBox version 5.0.14
* Operating system: CentOS 7
* Graphical environment: MATE
* Java JDK: OpenJDK 8
* Maven version 3.2.5
* MariaDB version 5.5.x

.VM Operating System Credentials

* The default username/password for the VM is `jboss/jboss`.
* The JBoss user has `sudo` access.

:numbered:

== Install VirtualBox and Lab VM

In this section you install VirtualBox on your local workstation. There are two methods: either download VirtualBox directly or use BitTorrent. If you are familiar with BitTorrent and have a BitTorrent client, this method is usually much faster and more reliable.

. Download the `gpte-bxms-advanced-infrastructure-630.vdi` VirtualBox image using one of the two methods:

* Direct: Download `gpte-bxms-advanced-infrastructure-630.vdi` directly from https://drive.google.com/open?id=0B8mmXW6hJKdiaVpndWxFV3Nmbkk


* BitTorrent: Download `gpte-bxms-advanced-infrastructure-630.torrent` found at https://github.com/gpe-mw-training/bxms-advanced-infrastructure-lab-etc/raw/master/etc/gpte-bpms-advanced-630.vdi.torrent. Using your BitTorrent client, open the torrent file and download `gpte-bxms-advanced-infrastructure-630.vdi`.

. Install VirtualBox on your local workstation by following instructions here: https://www.virtualbox.org/wiki/Downloads.
+
[NOTE]
The `gpte-bxms-advanced-infrastructure-630.vdi` is a 64-bit VM, so make sure that the `amd64` version of VirtualBox is installed and that virtualization is enabled in your host machine's BIOS. Refer to VirtualBox's online documentation for assistance in configuring it for your workstation.

. Start VirtualBox and navigate to: *Machine -> New*.
. In the *Create Virtual Machine* panel, populate its fields:
* *Name:* `gpte-bxms-advanced-infrastructure`
* *Type:* `Linux`
* *Version:* `Red Hat (64-bit)`
. Click *Next*.
. In the *Memory* panel, specify `4096 MB` of RAM and click *Next*.
. In the *Hard Disk* panel:
.. Select *Use an existing virtual hard disk file*.
.. Browse your hard drive and select the previously downloaded `gpte-bxms-advanced-infrastructure-630.vdi` image.
.. Click *Create*.
. Click *Start*.

== Install BPMS Business-Central and Kie-server on the virtual machine.

The virtual machine comes with a script that will install and configure BPMS Business-Central and Kie-server. +
The script will install a separate instance of Business-Central and Kie-server. This reflects a realistic installation setup where Business-Central is used at development time, where Kie-server is used as process/rules execution runtime.

To install the BPMS instances on the virtual machines:

. In the virtual machine, open a terminal window.
. Change to the `/home/jboss/lab` directory, and execute the `install-bpms.sh` script. Make sure to execute the script as user `jboss`. The script will create two instances of BPMS:
.. `home/jboss/lab/bpms/bc` : Business-Central workbench and DashBuilder. No Kie-server.
.. `home/jboss/lab/bpms/kieserver` : Kie-server execution runtime, no Business-Central nor DashBuilder.
. Review the `install-bpms.sh` script. The script itself delegates to the `install-bpms-instance.sh` script in the `/opt/install/scripts/bpms` directory.
. As part of the installation, a number of system properties have been set in the `standalone.conf` file in `home/jboss/lab/bpms/bc/bin` and `home/jboss/lab/bpms/kieserver/bin`. +
Review these system property values as they give a good idea of the system properties that should be set for a BPMS installation.
. The Kie-server instance is configured with a port-offset of 150 - the HTTP port will be 8230 rather than 8080. This allows to run both the Business-Central as the Kie-server instance concurrently.
. The installed instances are configured to use the built-in H2 database. As part of the labs you will complete the configuration to point to MariaDB instead.
. The Kie-server instance is configured as an unmanaged instance. If you would like to use the Business-Central instance as a controller for Kie-server, uncomment the following lines:
.. `home/jboss/lab/bpms/bc/bin/standalone.conf`
+
----
#JAVA_OPTS="$JAVA_OPTS -Dorg.kie.server.user=jboss"
#JAVA_OPTS="$JAVA_OPTS -Dorg.kie.server.pwd=bpms"
----
.. `home/jboss/lab/bpms/bc/bin/standalone.conf`
+
----
#JAVA_OPTS="$JAVA_OPTS -Dorg.kie.server.controller=http://127.0.0.1:8080/business-central/rest/controller"
#JAVA_OPTS="$JAVA_OPTS -Dorg.kie.server.controller.user=kieserver"
#JAVA_OPTS="$JAVA_OPTS -Dorg.kie.server.controller.pwd=kieserver1!"
----

== Lab Assets Overview

This course includes a lab asset projects that is publicly available in GitHub:

* *bxms-advanced-infrastructure-lab*
+
This project contains the BPM Suite KIE projects used in the labs, as well as an AngularJS web application to test integration with Red Hat SSO.


