:scrollbar:
:data-uri:
:noaudio:

== Optimistic and Pessimistic Locking

* By default JPA in JBoss BPM Suite engine uses optimistic locking strategy with versioning
* May lead to race conditions: `OptimisticLockException`
** Process definitions with wait states or asynchronous nodes in parallel branches
* Engine can recover from `OptimisticLockException`
** Failing branch is re-executed within same transaction
* JBoss BPM Suite engine can be configured to use pessimistic locking strategy
** JPA `PESSIMISTIC_FORCE_INCREMENT` lock mode
** To enable, set environment entry `org.kie.api.persistence.pessimistic` to `true` in KJAR deployment descriptor:
+
[source,xml]
----
    <environment-entries>
        <environment-entry>
            <name>org.kie.api.persistence.pessimistic</name>
            <resolver>mvel</resolver>
            <identifier>true</identifier>
        </environment-entry>
    </environment-entries>
----

ifdef::showscript[]

Transcript:

When process definitions with wait states or asynchronous nodes are used in parallel branches of a process, the process engine faces race conditions when it reaches the join gateway of both branches, which can can lead to `OptimisticLockExceptions`.

In such cases, the execution engine tries to re-execute the failing branch within the same transaction. This can lead to unwanted double execution of some nodes. This is because JBoss BPM Suite defaults to using an optimistic locking strategy with versioning.

There are cases when you may want to change this to a pessimistic locking strategy. To enable the JPA `PESSIMISTIC_FORCE_INCREMENT` lock mode, you must add an environment entry to the deployment descriptor `org.kie.api.persistence.pessimistic` with a `true` value identifier.

endif::showscript[]
