:scrollbar:
:data-uri:
:noaudio:

== Database Maintenance

* Runtime data cleaned up automatically:
** Process instance data (`ProcessInstanceInfo` table) removed upon completion of process instance
** Task instance data (`Task` and `Content` tables) removed upon completion of owning process
** Work item information (`WorkItemInfo` table) removed upon completion of work item
* Some data not removed:
** Audit data for processes and tasks
** Executor requests
** Persistent timers using Quartz


ifdef::showscript[]

Transcript:

The database might need some maintenance, but be aware that some runtime data is cleaned up automatically:

* The process instance data--stored in the ProcessInstanceInfo table--is removed upon completion of the process instance.
* The task instance data--stored in the Task and Content tables--is removed upon completion of the task owning process.
* The work item information--stored in the WorkItemInfo table--is removed upon completion of the work item.

However, the following data is not removed: audit data for processes and tasks, Executor requests information, and the persisted quartz timers.


endif::showscript[]
