:scrollbar:
:data-uri:
:noaudio:

== Persistence in JBoss BPM Suite

.Configuration and Deployments
* Business Central
** System Git repository
** Database (deployments)
* Realtime Decision Server, Intelligent Process Server
** File system for _unmanaged_ instances
** Business Central controller for _managed_ instances

ifdef::showscript[]

Transcript:

The configuration and deployments for Business Central and the Realtime Decision Server and Intelligent Process Server must also be persisted so that the configuration and deployments can survive a server restart.

To persist configuration and deployment information, Business Central uses the system Git repository and database.

The Realtime Decision Server and Intelligent Process Server use the file system to persist the configuration and deployments of unmanaged instances.

When these server instances are managed by a Business Central controller, they use Business Central to store configuration and deployment information. Business Central uses the system Git repository and database as stated.

endif::showscript[]
