:scrollbar:
:data-uri:


== Persistence Technology

* JPA--targets SQL database
* Individual deployments configured to not use persistence
* NoSQL databases not supported--community effort, not part of product

* Supported databases:
** Open source: PostgreSQL, MySQL/MariaDB
** Proprietary: Oracle, SQLServer, DB2, Sybase

* Default persistence settings in JBoss BPM Suite
** Embedded H2 in memory database
** Not supported in production

ifdef::showscript[]

Transcript:

By default JBoss BPM Suite is not configured to use persistence. To configure JBoss BPM Suite to use persistence, use JPA targeting an SQL database.

Some community effort configurations use NoSQL databases to persist runtime data. These configurations are not supported and are not part of the product.

Supported open-source databases include PostgreSQL and MySQL/MariaDB. The supported proprietary databases are Oracle, SQLServer, DB2, and Sybase.

The default persistence settings in JBoss BPM Suite use an embedded H2 in memory database. This persistence configuration is not recommended for production.

endif::showscript[]
