:scrollbar:
:data-uri:


== Client Targeting
.Container Resolution Process

Resolution of proper container ID performed by client by sequentially invoking methods:

. Process instance ID (BPM)
. Correlation key (BPM)
. Task instance ID (BPM)
. Work item ID (BPM)
. Job request ID (BPM)
. Conversation ID (KIE, BRM, BPM)
. Default container ID (KIE, BRM, BPM)

ifdef::showscript[]

Transcript:

The resolution of the proper container ID is performed by the client by invoking the following methods sequentially:

. The process instance ID is used to find the container that started the given process instance.
. The correlation key is used to find the container that started a process instance with the given correlation key.
. The task instance ID is used to find the container that has a process waiting for a given task ID conclusion.
. The work item ID is used to identify the container and the process ID.
. The job request ID.
. The conversation ID.
. Finally, the default container ID is used if the resolver was unable to find another container responsible for the execution.

endif::showscript[]
