:scrollbar:
:data-uri:
:noaudio:

== Container Naming

.Container Deployment

[[app-listing]]
[source,xml]
----
<kie-server-state>
  <containers>
    <container>
      <containerId>e8d626d14a44bf3cf1f127ae9fdabc91</containerId>
      <releaseId>
        <groupId>org.openshift.quickstarts</groupId>
        <artifactId>processserver-library</artifactId>
        <version>1.3.1.Final</version>
      </releaseId>
      <status>STARTED</status>
      <configItems/>
      <messages/>
    </container>
    <container>
      <containerId>9ba203be65a2e077551cc55bb886818a</containerId>
      <releaseId>
        <groupId>org.openshift.quickstarts</groupId>
        <artifactId>processserver-library</artifactId>
        <version>1.3.0.Final</version>
      </releaseId>
      <status>STARTED</status>
      <configItems/>
      <messages/>
    </container>
  </containers>
</kie-server-state>
----

ifdef::showscript[]

Transcript:

When the KIE containers are deployed to the Intelligent Process Server web application, an XML file is created with the deployments' information. The container ID hashes come from each unique KIE container deployment part.

For example, `e8d626d14a44bf3cf1f127ae9fdabc91` is the MD5 sum (hex binary) of `processserver-library=org.openshift.quickstarts:processserver-library:1.3.1.Final`.

The container ID overriding is done only if the `KIE_CONTAINER_REDIRECT_ENABLED` parameter is set to `true`. Otherwise, if multiple versions of the same KJAR are deployed with the same container ID in `KIE_CONTAINER_DEPLOYMENT`, only the _latest_ version of that KJAR container is deployed.

endif::showscript[]
