:scrollbar:
:data-uri:
:noaudio:

== Redirect Capability

The Decision Server and Process Server images provide multi-version tenancy capability of kjars for KIE Containers.

* Provides ability to run new versions of KIE containers concurrently with older versions of KIE containers in the same Decision Server pod.
* Support for older versions is especially important for stateful interactions. 
** A BPM process that might last months.

== Introduce New KIE Versions

* Set the KIE_CONTAINER_REDIRECT_ENABLED to true.
* Specify the KIE_CONTAINER_DEPLOYMENT_OVERRIDE variable inside the *./sti/environment* file
** Will override the KIE_CONTAINER_DEPLOYMENT variable in template
* When a new version is available, simply change the KIE_CONTAINER_DEPLOYMENT_OVERRIDE variable to include _both_ the old _and_ new container deployments using the _same_ container id, and commit to source control.
* The link:https://docs.openshift.com/enterprise/3.1/dev_guide/builds.html#webhook-triggers[GitHub Webhooks] mechanism can then pick up the updated *./sti/environment* file in source, triggering a new S2I build.

== Container Naming

The OpenShift KIE Server images allow multiple versions of the same kjars by overriding the original container id with a hash version including the version of the kjar.

Let's look at an example. Say you have the following environment set:

[[app-listing]]
[source,bash]
----
KIE_CONTAINER_DEPLOYMENT=processserver-library=org.openshift.quickstarts:processserver-library:1.3.0.Final|processserver-library=org.openshift.quickstarts:processserver-library:1.3.1.Final
KIE_CONTAINER_REDIRECT_ENABLED=true
----

The following containers will get deployed:

[[app-listing]]
[source,xml]
----
<kie-server-state>
  <containers>
    <container>
      <containerId>e8d626d14a44bf3cf1f127ae9fdabc91</containerId>
      <releaseId>
        <groupId>org.openshift.quickstarts</groupId>
        <artifactId>processserver-library</artifactId>
        <version>1.3.1.Final</version>
      </releaseId>
      <status>STARTED</status>
      <configItems/>
      <messages/>
    </container>
    <container>
      <containerId>9ba203be65a2e077551cc55bb886818a</containerId>
      <releaseId>
        <groupId>org.openshift.quickstarts</groupId>
        <artifactId>processserver-library</artifactId>
        <version>1.3.0.Final</version>
      </releaseId>
      <status>STARTED</status>
      <configItems/>
      <messages/>
    </container>
  </containers>
</kie-server-state>
----

Where did those containerId hashes come from? Each unique KIE Container deployment part. For example, *e8d626d14a44bf3cf1f127ae9fdabc91* is the MD5 sum (hex binary) of *processserver-library=org.openshift.quickstarts:processserver-library:1.3.1.Final*.

NOTE: The container id overriding is only done if the KIE_CONTAINER_REDIRECT_ENABLED parameter is set to true. Otherwise, if multiple versions of the same kjar are deployed with the same container id in KIE_CONTAINER_DEPLOYMENT, only the _latest_ version of that kjar/container will be deployed.

== Client Targeting

In most cases, clients have to target a particular container by name in order to execute server-side functions.
Given that the actual container ids on the server have been renamed, how can the client code do this? There are multiple ways:

* Full deployment part: *processserver-library=org.openshift.quickstarts:processserver-library:1.3.1.Final*
* Full deployment hash: *e8d626d14a44bf3cf1f127ae9fdabc91*
* Deployment alias: *processserver-library* (See Client Redirects below.)

== Client Alias Redirects

In the case where the deployment alias is used, the incoming request gets redireted to the specific deployed KIE Container in the server. There is a multi-step container-resolution process which is used to determine _which_ version of a container is targeted by the redirect. This process is followed in the REST interface by using a Servlet Filter, and in the JMS interface by using an EJB Interceptor. 

== Container Resolution Process

There are multiple clients that can be used to invoke the server, depending upon the work that needs to be done.

*KIE interaction*
* org.kie.server.client.KieServicesClient

*BRM interaction*
* org.kie.server.client.RuleServicesClient

*BPM interaction*
* org.kie.server.client.ProcessServicesClient
* org.kie.server.client.JobServicesClient
* org.kie.server.client.QueryServicesClient
* org.kie.server.client.UserTaskServicesClient

The process that is used to resolve the proper container id depends on the method that is invoked by each of these clients. The following list describes, in order, what is used to deduce the proper container:

* Process Instance Id (BPM)
* Correlation Key (BPM)
* Task Instance Id (BPM)
* Work Item Id (BPM)
* Job Request Id (BPM)
* Conversation Id (KIE, BRM, BPM)
* Default Container Id (KIE, BRM, BPM)

== Default Container Id

If a specific container id cannot be resolved, than a default container id is selected. 
The default container is determined as the _latest_ version of a kjar's releaseId (GAV) for the same container name. So in the above processserver-library example, the 1.3.1.Final version is the latest and thus default, not the 1.3.0.Final version.

ifdef::showscript[]

endif::showscript[]
