:scrollbar:
:data-uri:
:noaudio:

== `UserGroupCallback`

.Configuration

* In Process Server, alternative implementations can be plugged in through system properties
* To use provided LDAP implementation:
** `org.jbpm.ht.callback=ldap`
** `jbpm.usergroup.callback.properties=<URI of callback configuration file>`
* To use custom implementation:
** `org.jbpm.ht.callback=custom`
** `org.jbpm.ht.custom.callback=<FQN of implementation class>`

ifdef::showscript[]

In order to provide an UserGroupCallback implementation one can use the `org.jbpm.ht.callback` property and provide the implementation name. The implementation name options are:
* *mvel*: Default; mostly used for testing.
* *ldap*: LDAP; requires additional configuration in the `jbpm.usergroup.callback.properties` file.
* *db*: Database; requires additional configuration in the `jbpm.usergroup.callback.properties` file.
* *jaas*: JAAS; delegates to the container to fetch information about user data.
* *props*: A simple property file; requires additional file that will keep all information (users and groups).
* *custom*: A custom implementation; you must specify the fully qualified name of the class in the `org.jbpm.ht.custom.callback`.

The most commonly configured options are `ldap` and `custom`.
When using `ldap`: one must also provide a properties file in the `jbpm.usergroup.callback.properties` property.
When using `custom`: one must also provide with the Fully Qualified Class Name of the custom UserGroupCallback implementation class name in the `org.jbpm.ht.custom.callback` property

endif::showscript[]
