:scrollbar:
:data-uri:
:noaudio:

== Bypass Authenticated User

* Log in to Process Server with a _system_ user.
* Task operations performed on behalf of a real user.
* Real username passed in as query parameter to the Remote API.
* Front-end applications do not require knowledge of user passwords.
* Enable with system property `org.kie.server.bypass.auth.user=true`
* When enabled, requires configuration of a `UserGroupCallBack` implementation.
** Default callback returns the group information of the system user.

ifdef::showscript[]

In some cases it will be easier for an external application to connect to the process server using a _system_ user and perform task operations on behalf of a real user.
This is useful to simplify the authentication to the process server as a back-end resource of your application.
When logging in to the Process Server with a _system_ user and performing operations on behalf of a real user we say that we are `Bypassing authenticated user`: The Real user name is passed in as a query parameter to the Remote API. Thus the Front-end application do not require knowledge of user passwords.
In order to enable `Bypass authenticated user` one must set the `org.kie.server.bypass.auth.user` property with a value of `true`. When `Bypass authenticated user` is enabled: requires configuration of a custom `UserGroupCallback` implementation. The custom `UserGroupCallback` implementation is required because the default callback returns the group information of the system user, not the bypassed user.

endif::showscript[]
