:scrollbar:
:data-uri:


== Security in JBoss BPM Suite
* Business Central UI application
* Business Central remote APIs
* Realtime Decision Server and Intelligent Process Server remote APIs
* Intelligent Process Server for OpenShift remote APIs
* JBoss BPM Suite: User Tasks resolution for users and groups

ifdef::showscript[]

Transcript:

When thinking about the security implementation for JBoss BPM Suite authentication and authorization, consider the following:

* *Business Central UI application*: You must implement the way that users are authenticated by the Business Central UI application to be able to instantiate processes and work in Human Tasks.
* *Business Central remote APIs*: Not all users need access to all Business Central commands through the REST APIs. You need to think about and define the way that different users and groups interact with the Business Central remote APIs.
* *Realtime Decision Server and Intelligent Process Server remote APIs*: You also need to define the way that users interact with these APIs to provide authentication and authorization granularity for the remote APIs.
* *Intelligent Process Server for OpenShift remote APIs*: When defining a cloud-based environment, you also need to consider how users authenticate and how to integrate their permissions with the Intelligent Process Server.
* *JBoss BPM Suite User Tasks resolution for users and groups*: By using the interfaces that interact with process execution and users and groups, you can implement a custom method to add even more granularity.

endif::showscript[]
