:scrollbar:
:data-uri:
:noaudio:

== Summary

* JBoss BRMS Realtime Decision Server
* CI/CD KIE Container Deployment
* Realtime Decision Server
* Batch Execution
* Realtime Decision Server for OpenShift
* Unmanaged Realtime Decision Server Only
* Stateless Ksession Only
* Runtime Rules Engine Only
* Realtime Decision Server for OpenShift Deployment
* Realtime Decision Server for OpenShift


ifdef::showscript[]

Transcript:

This module described configuring Red Hat OpenShift Container Platform for the Red Hat Realtime Decision Server container. The module began with an introduction to the JBoss BRMS Realtime Decision Server and CI/CD KIE container deployment. Next the Realtime Decision Server was discussed in more detail, including the REST API, the batch API and batch execution, and its availability as a containerized OpenShift image. Managed and unmanaged server administration were covered, as well as source-to-image deployment. The module concluded with a look at the Realtime Decision Server for OpenShift.

endif::showscript[]
