:scrollbar:
:data-uri:
:noaudio:

== Realtime Decision Server for OpenShift

.Parameters

* `MAVEN_MIRROR_URL`
** URL of local Maven server that _mirrors_ all _external_ Maven repositories
** Value included in custom `<mirror/>` entry in application project's `pom.xml`
** Used to pull Maven dependencies during S2I
** Used to pull built KJAR application if using binary deployment approach

* `KIE_CONTAINER_DEPLOYMENT`
** Specifies unique identifier of Drools applications that execute in Realtime Decision Server
** Format convention pipe-delimited: `containerId=groupId:artifactId:version|c2=g2:a2:v2`

ifdef::showscript[]

Transcript:

The `MAVEN_MIRROR_URL` parameter represents the URL to the local Maven server that mirrors all external Maven repositories. This value is included in the custom `<mirror/>` entry in the application project's `pom.xml` file. It is used to pull the Maven dependencies during S2I. It is also used to pull a built KJAR application if the binary deployment approach is used.

The `KIE_CONTAINER_DEPLOYMENT` parameter specifies one or more KJAR projects to be initialized as KIE containers. The different deployment units can be pipe-delimited.

endif::showscript[]
