:scrollbar:
:data-uri:


== Unmanaged Realtime Decision Server Only

* JBoss BPM Suite allows for _unmanaged_ and _managed_ administration of Realtime Decision Server and Intelligent Process Server
* Realtime Decision Server for OpenShift leverages only _unmanaged_ approach
** OpenShift by default handles application pod management (HA and scalability)
* Example _unmanaged_ XML found in `$JBOSS_HOME` of Realtime Decision Server pod:
+
[source,xml]
-----
<kie-server-state>
  <controllers/>
  <configuration>
    <configItems>
      <config-item>
        <name>org.kie.server.repo</name>
        <value>.</value>
        <type>java.lang.String</type>
      </config-item>
      <config-item>
        <name>org.kie.server.id</name>
        <value>kieserver</value>
        <type>java.lang.String</type>
      </config-item>
    </configItems>
  </configuration>
  <containers class="linked-hash-set">
    <container>
      <containerId>policyquote</containerId>
      <releaseId>
        <groupId>com.redhat.gpte.xpaas</groupId>
        <artifactId>policyquote</artifactId>
        <version>1.0-SNAPSHOT</version>
      </releaseId>
      <status>STARTED</status>
      <configItems/>
      <messages/>
    </container>
  </containers>
</kie-server-state>
-----

ifdef::showscript[]

Transcript:

JBoss BPM Suite allows for _unmanaged_ and _managed_ administration of Realtime Decision Server and Intelligent Process Server, but the Realtime Decision Server for OpenShift leverages only the _unmanaged_ approach. OpenShift by default handles application pod management.

endif::showscript[]
