:scrollbar:
:data-uri:
:noaudio:

== Realtime Decision Server for OpenShift

.Parameters

* `SOURCE_REPOSITORY_URL`
** URL to version-controlled application source code
** Used during S2I

* `SOURCE_REPOSITORY_REF`
** Git branch/tag reference
** Default: `Master`
** Used during S2I

* `CONTEXT_DIR`
** Path within Git project to build
** Used during S2I

ifdef::showscript[]

Transcript:

When using the Decision Server template from the Red Hat registry, the template supports parameters to tune up the runtime and provide information about the KIE containers that need to be initialized.

The supported parameters are:

* `SOURCE_REPOSITORY_URL`, which represents the URL to version-controlled application source code. This parameter is used during S2I approach to specify the source code location. Generally it refers to a Git repository.

* `SOURCE_REPOSITORY_REF`, which represents the Git branch or tag to reference. When using `SOURCE_REPOSITORY_URL`, the default value for `SOURCE_REPOSITORY_REF` is `Master`. You can specify a different branch name.

* `CONTEXT_DIR`: You can specify a path within the `SOURCE_CODE_REPOSITORY` to be built during S2I approach.

endif::showscript[]
