:scrollbar:
:data-uri:
:noaudio:

== OCP Decision Server Deployment

* S2I deployment:
** No proper version management of built artifact
** Kjar rebuilt from source at every deployment
** Violates _build once, deploy everywhere_ principle
** Tests not executed as part of S2I build

* Prebuild kjar binary deployment:
** Typically involves use of OpenShift Jenkins image and Groovy-based workflow plug-in

* In both approaches:
** Kjar and dependencies make it to `~/.m2/` repository of Decision Server pod
** Decision Server then reads `unmanaged` `kie-server-state` XML configs to create KIE Container


ifdef::showscript[]

When deploying the Decision Server to OCP we have 2 main options:
1. Source 2 Image Deployment.
2. Binary deployment.
When using the Source 2 Image deployment the kjar is rebuilt from source code at every deployment. This can be useful during the development phase, but there is no proper version management of the built artifact, the tests are not executed as part of the S2I build and violates the _build once, deploy everywhere_ principle.
When using the Binary Deployment: a prebuilt binary kjar is used through OpenShift Jenkins image and the Groovy-based workflow plug-in.
In both approaches the kjar and its dependencies are created in the `~/.m2/` repository of the Decision Server pod, then the Decision Server reads the `unmanaged` `kie-server-state` XML configuration files to create the KIE Container.

endif::showscript[]
