:scrollbar:
:data-uri:
:noaudio:

== xPaaS Decision Server

.Deployment

* S2I deployment:
** No proper version management of built artifact
** Kjar rebuilt from source at every deployment
** Violates _build once, deploy everywhere_ principle
** Tests not executed as part of S2I build
* Prebuild kjar binary deployment:
** Typically involves use of OpenShift Jenkins image and Groovy-based workflow plug-in

* In both approaches:
** Kjar and dependencies make it to `~/.m2/` repository of Decision Server pod
** Decision Server then reads `unmanaged` `kie-server-state` XML configs to create KIE Container


ifdef::showscript[]

Research what differentiates between a S2I and a binary type build:

- For both labs of this module, a BuildConfig object of type GIT is used
    - this is different than typical OCP build options
        - Git Repo Source :  BuildConfig.spec.source.type = Gt 
        - Binary Source   :  BuildConfig.spec.source.type = Binary
- For both labs of this module, SOURCE_REPOSITORY_URL parameter is used:
  - 1st lab:  references URL of rules based policyquote kproject 
    - appears that kproject build as part of jboss eap s2i and kjar artifacts end up in $JBOSS_HOME/server/deployments
    - kieserver-install.sh inspects $JBOSS_HOME/server/deployments and moves kjars to ~/.m2/repository
    - kieserver-pull.sh pulls all additional maven dependencies to ~/.m2/repository
  - 2nd lab:  references URL of policyquote-ocp (containing only .s2/environment file)
    - no kjars in $JBOSS_HOME/server/deployments; kie-server-install.sh doesn't move anything
    - kieserver-pull.sh pulls all kjars and additional dependencies to ~/.m2/repository

Research how the KIE Containers get created in the OCP KIE Server ?
    - ultimately, kjars and dependencies appear to end up in local ~/.m2/repository
    - what creates KIE containers from the KJars ?
        - something in: https://github.com/jboss-openshift/openshift-kieserver ?


endif::showscript[]
